[package]
name = "tension_field"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
toybox = { git = "https://github.com/PORTALSURFER/toybox.git", rev = "afbb137b601383fe51d1e60f0a9512e6e47e009b" }

[target.'cfg(target_os = "windows")'.dependencies]
toybox = { git = "https://github.com/PORTALSURFER/toybox.git", rev = "afbb137b601383fe51d1e60f0a9512e6e47e009b", features = ["gui"] }

[build-dependencies]
toybox = { git = "https://github.com/PORTALSURFER/toybox.git", rev = "afbb137b601383fe51d1e60f0a9512e6e47e009b" }

[features]
default = []
screenshot-test = ["toybox/screenshot-test"]
